plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.hoyo'
version = '0.0.1-SNAPSHOT'
description = 'Translator'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2025.1.1")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-redis-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

    implementation 'com.github.ben-manes.caffeine:caffeine'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6' // Swagger UI
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

//THIS BE THE PART THAT DOWNLOADS THE FILES

def isWindows = System.getProperty('os.name').toLowerCase().contains('windows')
def pythonCommand
if (isWindows) {
    def venv1 = new File('scripts/.venv')
    def venv2 = new File('scripts/venv')

    if (venv1.exists()) {
        pythonCommand = 'scripts\\.venv\\Scripts\\python'
    } else if (venv2.exists()) {
        pythonCommand = 'scripts\\venv\\Scripts\\python'
    } else {
        pythonCommand = 'py'
    }
} else {
    def linuxVenv = new File(projectDir, 'scripts/venv/bin/python3')
    pythonCommand = linuxVenv.exists() ? linuxVenv.absolutePath : 'python3'
}

tasks.register('syncTextMaps', Exec) {
    commandLine pythonCommand, 'scripts/sync_files.py'

    standardOutput = System.out
    errorOutput = System.err
}

tasks.register('syncAssets', Exec) {
    commandLine pythonCommand, 'scripts/sync_assets.py'

    standardOutput = System.out
    errorOutput = System.err
}

processResources.dependsOn(syncTextMaps)
processResources.dependsOn(syncAssets)