application.title=translator
application.version=1.0.0

spring.application.name=translator

server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.data.redis.host=192.168.29.105
spring.data.redis.port=6379