application.title=translator
application.version=1.0.0

spring.application.name=translator

server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.hostname}:${server.port}:${random.value}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis-orexis}
spring.data.redis.port=6379

spring.cache.type=caffeine

scheduler.hsr.checkForUpdate=true
translator.data.refresh-cron=0 0 3 */3 * ?
translator.data.directory=./data
translator.data.refresh-lock-key=translator:refresh:lock
translator.data.refresh-lock-ttl-seconds=3600

management.endpoints.web.exposure.include=health,info,logfile,metrics
management.endpoint.logfile.enabled=true
logging.file.name=/app/logs/${spring.application.name}.log
spring.output.ansi.enabled=ALWAYS